# Generated by Django 6.0.5 on 2026-06-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('headline', models.CharField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(unique=True)),
                ('skills', models.JSONField(default=list)),
                ('match_score', models.IntegerField(default=0)),
                ('outreach_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Contacted', 'Contacted'), ('Replied', 'Replied'), ('Interviewing', 'Interviewing'), ('Hired', 'Hired')], default='Contacted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roles', models.ManyToManyField(blank=True, to='roles.role')),
            ],
        ),
    ]
