# Generated by Django 6.0.5 on 2026-06-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='experiences',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
