# Generated by Django 6.0.5 on 2026-06-02 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_skills', models.JSONField(blank=True, default=list)),
                ('target_location', models.CharField(blank=True, max_length=200)),
                ('experience_min', models.CharField(blank=True, max_length=300)),
                ('message_tone', models.CharField(choices=[('Professional', 'Professional'), ('Friendly', 'Friendly'), ('Formal', 'Formal')], default='Professional', max_length=25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.role')),
            ],
        ),
    ]
